import { ApprovalItem, ChatMessage, InventoryProduct, SqlQueryItem, SubAgentTelemetry, Transaction } from '../types';

export const INITIAL_APPROVALS: ApprovalItem[] = [
  {
    id: 'po-1',
    refCode: '#PO-2024-918',
    title: 'Draft Purchase Order',
    supplierOrClient: 'Flour Mills of Nigeria Plc',
    amount: 820000,
    risk: 'Medium',
    category: 'Purchase Order',
    agentSource: 'Procurement Agent',
    description: 'Auto-generated by Procurement Agent. Restocks 120 units of vegetable oil to prevent inventory starvation. Human authorization required before payment dispatch.',
    status: 'pending',
    date: 'Today, 10:38 AM',
    details: {
      items: [
        { name: 'Golden Penny Pure Vegetable Oil 5L (Carton of 4)', qty: 30, unitPrice: 24500, total: 735000 },
        { name: 'Direct Pallet Logistics & Offloading Levy', qty: 1, unitPrice: 85000, total: 85000 }
      ],
      justification: 'Stockout projected in 14 hours at Ikeja depot based on weekend sales run-rate. Current stock: 18 units.',
      impact: 'Prevents estimated ₦1,420,000 in lost weekend retail sales and preserves B2B contract fulfillment.'
    }
  },
  {
    id: 'cr-2',
    refCode: '#CR-2024-402',
    title: 'Credit Limit Extension Request',
    supplierOrClient: 'Alaba Electronics & Provisions Mart',
    amount: 1500000,
    risk: 'Medium',
    category: 'Credit Limit',
    agentSource: 'Finance Agent',
    description: 'B2B client requesting Net-14 payment window increase from ₦2.5M to ₦4.0M for FMCG bulk stocking.',
    status: 'pending',
    date: 'Today, 09:15 AM',
    details: {
      items: [
        { name: 'Dangote Refined Sugar 50kg (50 Bags)', qty: 50, unitPrice: 30000, total: 1500000 }
      ],
      justification: 'Historical payment on-time rate is 98.2% across 14 previous cycles with Zero bad-debt record.',
      impact: 'Secures exclusive weekly bulk purchase rights against competitors in Trade Fair market.'
    }
  },
  {
    id: 'pr-3',
    refCode: '#PR-2024-119',
    title: 'Emergency Fuel & Fleet Disbursement',
    supplierOrClient: 'TotalEnergies Depot - Ikeja Central',
    amount: 320000,
    risk: 'Low',
    category: 'Disbursement',
    agentSource: 'Logistics Agent',
    description: 'Bulk diesel procurement (250 Liters @ ₦1,280/L) for 150kVA standby generator and two delivery vans.',
    status: 'pending',
    date: 'Today, 08:30 AM',
    details: {
      items: [
        { name: 'Automotive Gas Oil (Diesel) 250 Liters', qty: 250, unitPrice: 1280, total: 320000 }
      ],
      justification: 'Main grid power cut in Industrial Estate; cold storage and automated checkout server uptime required.',
      impact: 'Maintains refrigeration for dairy lines and sustains real-time POS processing through peak trade.'
    }
  }
];

export const INITIAL_AGENTS: SubAgentTelemetry[] = [
  {
    id: 'agent-ceo',
    name: 'AI CEO Orchestrator',
    role: 'Multi-Agent Synthesis & Executive Decisions',
    status: 'active',
    autonomy: 'Autonomous',
    accuracy: 98.7,
    actionsToday: 142,
    tools: ['Postgres Tool Layer', 'Cross-Agent Dispatcher', 'Executive Voice Synthesizer', 'WhatsApp Mirror'],
    lastAction: 'Synthesized morning operational vitality brief',
    avatarIcon: 'neurology'
  },
  {
    id: 'agent-finance',
    name: 'Finance & Settlement Agent',
    role: 'Realtime Cashflow, POS & NIBSS Reconciliation',
    status: 'active',
    autonomy: 'Autonomous',
    accuracy: 99.4,
    actionsToday: 328,
    tools: ['Paystack Webhook API', 'NIBSS Settlement Gateway', 'Zenith Bank API', 'Postgres Double-Entry Ledger'],
    lastAction: 'Reconciled ₦4,850,200 across 114 transactions with 0 discrepancy',
    avatarIcon: 'payments'
  },
  {
    id: 'agent-inventory',
    name: 'Inventory & Stock Agent',
    role: 'Stock Velocity, Shelf-life & Shortage Predictor',
    status: 'warning',
    autonomy: 'Semi-Autonomous',
    accuracy: 96.2,
    actionsToday: 89,
    tools: ['Ikeja Barcode Scanner Net', 'VI Warehouse RFID', 'Lead-Time Monte Carlo Predictor'],
    lastAction: 'Flagged Golden Penny 5L Oil stockout danger (14h remaining)',
    avatarIcon: 'inventory_2'
  },
  {
    id: 'agent-sales',
    name: 'Sales & Deals Pulse Agent',
    role: 'Rep Pacing, Storefront Quotas & CRM',
    status: 'active',
    autonomy: 'Autonomous',
    accuracy: 97.8,
    actionsToday: 215,
    tools: ['POS CRM Feed', 'WhatsApp B2B Bot', 'Tiered Pricing Engine'],
    lastAction: 'Tracked Blessing O. milestone (38 deals, ₦1.92M volume)',
    avatarIcon: 'military_tech'
  },
  {
    id: 'agent-procure',
    name: 'Procurement Agent',
    role: 'Supplier Price Indexing & Automated POs',
    status: 'active',
    autonomy: 'Semi-Autonomous',
    accuracy: 98.1,
    actionsToday: 47,
    tools: ['Flour Mills Direct EDI', 'Dangote B2B Exchange', 'PO Generation Engine'],
    lastAction: 'Drafted #PO-2024-918 for executive human authorization',
    avatarIcon: 'gavel'
  },
  {
    id: 'agent-logistics',
    name: 'Logistics & Fleet Agent',
    role: 'Inter-Branch Transit, Fuel & Dispatch',
    status: 'active',
    autonomy: 'Autonomous',
    accuracy: 95.5,
    actionsToday: 76,
    tools: ['Lagos Traffic GPS API', 'Fleet Fuel Gauge Sensor', 'Waybill QR System'],
    lastAction: 'Dispatched Van #3 from Ikeja to VI Branch (ETA: 42 mins)',
    avatarIcon: 'local_shipping'
  },
  {
    id: 'agent-tax',
    name: 'Tax & Compliance Agent',
    role: 'FIRS VAT / WHT Calculation & Audit Trail',
    status: 'active',
    autonomy: 'Autonomous',
    accuracy: 99.9,
    actionsToday: 64,
    tools: ['FIRS Tax Engine', 'Withholding Audit Validator', 'Statutory Ledger'],
    lastAction: 'Calculated 7.5% VAT reserve for daily settlements (₦363,765)',
    avatarIcon: 'verified'
  },
  {
    id: 'agent-support',
    name: 'WhatsApp B2B Conversational Agent',
    role: '24/7 Client Order Desk & Invoicing',
    status: 'active',
    autonomy: 'Autonomous',
    accuracy: 96.9,
    actionsToday: 184,
    tools: ['WhatsApp Business Cloud API', 'Product Catalog Parser', 'Instant Invoice PDF Generator'],
    lastAction: 'Auto-confirmed 12 bulk rice carton inquiries from Trade Fair merchants',
    avatarIcon: 'chat'
  }
];

export const INITIAL_SQL_QUERIES: SqlQueryItem[] = [
  {
    id: 'sql-1',
    agent: 'Finance Agent',
    query: `SELECT SUM(amount) AS gross_receipts, payment_channel, COUNT(*) AS txn_count
FROM tbl_sales_receipts
WHERE date_trunc('day', created_at) = CURRENT_DATE
GROUP BY payment_channel;`,
    executionTimeMs: 1.8,
    rowsReturned: 3,
    tablesTouched: ['tbl_sales_receipts', 'tbl_pos_terminals'],
    timestamp: '10:41:58 AM',
    status: 'success'
  },
  {
    id: 'sql-2',
    agent: 'Inventory Agent',
    query: `SELECT p.sku, p.name, i.current_qty, i.burn_rate_per_hour,
       (i.current_qty / NULLIF(i.burn_rate_per_hour, 0)) AS hours_remaining
FROM tbl_inventory_stock i
JOIN tbl_products p ON i.product_id = p.id
WHERE (i.current_qty / NULLIF(i.burn_rate_per_hour, 0)) < 24
ORDER BY hours_remaining ASC;`,
    executionTimeMs: 2.4,
    rowsReturned: 1,
    tablesTouched: ['tbl_inventory_stock', 'tbl_products'],
    timestamp: '10:41:59 AM',
    status: 'success'
  },
  {
    id: 'sql-3',
    agent: 'Sales Agent',
    query: `SELECT s.rep_name, COUNT(o.id) as deals_count, SUM(o.total_amount) as revenue
FROM tbl_sales_reps s
JOIN tbl_orders o ON s.id = o.rep_id
WHERE o.created_at >= CURRENT_DATE
GROUP BY s.rep_name
ORDER BY revenue DESC
LIMIT 1;`,
    executionTimeMs: 1.2,
    rowsReturned: 1,
    tablesTouched: ['tbl_sales_reps', 'tbl_orders'],
    timestamp: '10:42:00 AM',
    status: 'success'
  },
  {
    id: 'sql-4',
    agent: 'Procurement Agent',
    query: `SELECT po.id, po.po_number, po.vendor_name, po.total_value, po.risk_level
FROM tbl_purchase_orders po
WHERE po.status = 'PENDING_HUMAN_AUTH'
AND po.tenant_id = 'balogun_mega_traders';`,
    executionTimeMs: 0.9,
    rowsReturned: 1,
    tablesTouched: ['tbl_purchase_orders'],
    timestamp: '10:42:01 AM',
    status: 'success'
  },
  {
    id: 'sql-5',
    agent: 'Finance Agent',
    query: `SELECT time_bucket('30 minutes', created_at) AS bucket, SUM(amount) as velocity
FROM tbl_settlement_events
WHERE created_at >= CURRENT_DATE + interval '7 hours'
GROUP BY bucket
ORDER BY bucket ASC;`,
    executionTimeMs: 3.1,
    rowsReturned: 6,
    tablesTouched: ['tbl_settlement_events'],
    timestamp: '10:42:01 AM',
    status: 'success'
  },
  {
    id: 'sql-6',
    agent: 'AI CEO Orchestrator',
    query: `SELECT system_health_score, active_subagent_count, pending_hitl_count
FROM v_enterprise_orchestrator_state
WHERE location_id = 'VI_HQ';`,
    executionTimeMs: 0.7,
    rowsReturned: 1,
    tablesTouched: ['v_enterprise_orchestrator_state'],
    timestamp: '10:42:02 AM',
    status: 'success'
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-101',
    time: '10:44 AM',
    customer: 'Mega-Mart Supermarkets',
    method: 'NIBSS Instant Transfer',
    branch: 'Victoria Island',
    amount: 1450000,
    status: 'Settled',
    reference: 'NIBSS-90481239'
  },
  {
    id: 'tx-102',
    time: '10:39 AM',
    customer: 'Walk-in Retail Buyer (Lekki)',
    method: 'Paystack POS',
    branch: 'Victoria Island',
    amount: 125000,
    status: 'Settled',
    reference: 'PSTK-481903'
  },
  {
    id: 'tx-103',
    time: '10:31 AM',
    customer: 'De-God Grace Eatery',
    method: 'NIBSS Instant Transfer',
    branch: 'Ikeja Depot',
    amount: 780000,
    status: 'Settled',
    reference: 'NIBSS-90481224'
  },
  {
    id: 'tx-104',
    time: '10:20 AM',
    customer: 'Blessing O. Trade Order #481',
    method: 'Paystack POS',
    branch: 'Ikeja Depot',
    amount: 640000,
    status: 'Settled',
    reference: 'PSTK-481877'
  },
  {
    id: 'tx-105',
    time: '10:05 AM',
    customer: 'Ikeja Wholesale Cashier 2',
    method: 'Cash Deposit',
    branch: 'Ikeja Depot',
    amount: 320000,
    status: 'Settled',
    reference: 'CSH-002910'
  },
  {
    id: 'tx-106',
    time: '09:48 AM',
    customer: 'Prime Choice Bakeries',
    method: 'NIBSS Instant Transfer',
    branch: 'Victoria Island',
    amount: 1535200,
    status: 'Settled',
    reference: 'NIBSS-90481190'
  }
];

export const INITIAL_INVENTORY: InventoryProduct[] = [
  {
    id: 'inv-1',
    sku: 'SKU-OIL-GP5L',
    name: 'Golden Penny Pure Vegetable Oil (5L)',
    category: 'Cooking Oils & Fats',
    stockLevel: 18,
    unit: 'Cartons (x4)',
    reorderPoint: 50,
    leadTimeDays: 2,
    burnRateHours: 14,
    status: 'critical',
    branch: 'Ikeja Depot',
    supplier: 'Flour Mills of Nigeria Plc'
  },
  {
    id: 'inv-2',
    sku: 'SKU-SUG-D50K',
    name: 'Dangote Refined White Sugar (50kg)',
    category: 'Commodities',
    stockLevel: 142,
    unit: 'Bags',
    reorderPoint: 80,
    leadTimeDays: 1,
    burnRateHours: 96,
    status: 'healthy',
    branch: 'Victoria Island',
    supplier: 'Dangote Sugar Refinery Plc'
  },
  {
    id: 'inv-3',
    sku: 'SKU-RICE-MG50K',
    name: 'Mama Gold Premium Parboiled Rice (50kg)',
    category: 'Grains & Staple',
    stockLevel: 64,
    unit: 'Bags',
    reorderPoint: 60,
    leadTimeDays: 3,
    burnRateHours: 32,
    status: 'warning',
    branch: 'Ikeja Depot',
    supplier: 'Olam Agri Nigeria'
  },
  {
    id: 'inv-4',
    sku: 'SKU-FLR-HW50K',
    name: 'Honeywell Superfine Wheat Flour (50kg)',
    category: 'Baking Essentials',
    stockLevel: 95,
    unit: 'Bags',
    reorderPoint: 40,
    leadTimeDays: 2,
    burnRateHours: 120,
    status: 'healthy',
    branch: 'Victoria Island',
    supplier: 'Honeywell Flour Mills Plc'
  },
  {
    id: 'inv-5',
    sku: 'SKU-BEV-MILO',
    name: 'Nestlé Milo Energy Food Drink (500g)',
    category: 'Beverages & Dairy',
    stockLevel: 210,
    unit: 'Cartons',
    reorderPoint: 75,
    leadTimeDays: 2,
    burnRateHours: 180,
    status: 'healthy',
    branch: 'Victoria Island',
    supplier: 'Nestlé Nigeria Plc'
  }
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender: 'user',
    senderName: 'Alhaji Balogun (You)',
    timestamp: '10:42 AM',
    content: 'How is my business doing today and what needs my immediate attention?'
  },
  {
    id: 'msg-2',
    sender: 'agent',
    senderName: 'KoraOps CEO Agent',
    timestamp: 'Just now',
    operationalVitality: {
      healthScore: 94,
      headline: 'Strong morning sales in Ikeja branch, but 2 critical bottlenecks require executive authorization.'
    },
    velocityMetric: {
      label: 'Realtime Settlement Velocity',
      changeText: '+18.4% vs Yesterday',
      bars: [
        { time: '07:00', heightPercent: 35 },
        { time: '08:30', heightPercent: 45 },
        { time: '', heightPercent: 60 },
        { time: '10:00', heightPercent: 50 },
        { time: '', heightPercent: 80, isHighlight: true },
        { time: 'Current', heightPercent: 100, isHighlight: true }
      ]
    },
    telemetryReports: [
      {
        id: 'rep-fin',
        agentName: 'Finance Agent Report',
        agentType: 'finance',
        badge: 'Reconciled',
        badgeVariant: 'success',
        body: '₦4,850,200 in gross receipts. 91% collected via instant NIBSS bank transfer & Paystack POS. OpEx today: ₦320,000 (diesel generator fueling & delivery logistics).'
      },
      {
        id: 'rep-inv',
        agentName: 'Inventory Agent',
        agentType: 'inventory',
        badge: 'Stock Warning',
        badgeVariant: 'warning',
        body: 'Critical warning: Golden Penny Vegetable Oil (5L) stockout projected within 14 hours. Supplier Lead time: 2 days.'
      },
      {
        id: 'rep-sales',
        agentName: 'Sales Agent Pulse',
        agentType: 'sales',
        badge: '38 Deals',
        badgeVariant: 'info',
        body: 'Top rep: Blessing O. (₦1,920,000 closed today)',
        avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8XDITV4k_nQXwDkINIU9om1fvWJhOLOln9XXmjYHEyKqQU2VmyWYEs8oliyOZKlgKRNCQuD0BTiCSIR3m3TGyowxTCmVWL4YcWp1H6gLo8vBslG0FUFNuv9x07d7LpBDYroS8VSKszFOIOvDvIcdeyY2q1JgiMEhiwiDEima23WT2uy5VINWlwX-6tdh0ArJodGuW91XMUgyPnuJIH2hAGBWV-ApfzQwKGmKyjcJCbK3DX8zGmM2SkQ',
        repName: 'Blessing O.',
        dealsCount: '38 Deals'
      }
    ],
    pendingAuthorization: INITIAL_APPROVALS[0],
    sqlCount: 12
  }
];
